expo.modules.updates.EXPO_RELEASE_CHANNEL=staging  
expo.modules.updates.EXPO_UPDATE_URL=https://u.expo.dev/6bd54667-5b96-4972-a542-a6527965e89a  
expo.modules.updates.EXPO_RUNTIME_VERSION=1.0.0  
expo.modules.updates.ENABLED=true 
